checks:
  java: true

build:
#  dependencies:
#    override:
#      - true

  environment:
    memcached: false
    postgresql: false
    redis: false
    mysql: false
    neo4j: false
    rabbitmq: false
    elasticsearch: false

  nodes:
    analysis:
      tests:
        override:
          - java-scrutinizer-run
          -
            command: mvn findbugs:findbugs
            analysis:
              file: /home/scrutinizer/build/target/findbugs/findbugsXml.xml
              format: findbugs-xml
          -
            command: java-sonar-run
            use_website_config: true
            idle_timeout: 600
          -
            command: mvn pmd:pmd
            analysis:
              file: /home/scrutinizer/build/target/pmd/pmd.xml
              format: pmd-xml

  tests:
    override:
      -
        command: false

filter:
  excluded_paths:
    - .github
    - config
    - design-docs
    - docs
    - sample-scenarios
    - modules/integration
